language: php

php:
  - 7.0
  - 7.1

before_install:
  - composer self-update
  - mysql -e 'CREATE DATABASE spiral;'
  - psql -c 'create database spiral;' -U postgres

install:
  - composer install --no-interaction --prefer-source

script:
  - phpunit